# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
            ],
        ),
    ]
