# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
