# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0003_addstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddStudentByEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(max_length=200, unique=True, verbose_name=b'email address')),
            ],
        ),
        migrations.DeleteModel(
            name='AddStudent',
        ),
    ]
